--SUB -queries  
--Sufficient Where Condition were used when necessary in backends
--1

--ekta medicine ki porimane goto x dine USE
SELECT
    M.MedicineID,
    M.MedicineName,
    (
        SELECT COUNT(*)
        FROM PRESCRIBEDMEDICINE PM
        JOIN ALLMEDICINEPRESCRIBERMEDICINERELATION AMR ON PM.PrescribedMedicineID = AMR.PrescribedMedicineID
        JOIN MEDICINES M2 ON AMR.MedicineID = M2.MedicineID
        JOIN PRESCRIPTION P ON PM.PrescriptionID = P.PrescriptionID
        WHERE M2.MedicineID = M.MedicineID
          AND P.PRESCRIPTIONDATE >= SYSDATE - 15
    ) AS UsageCount
FROM
    MEDICINES M;
---
SELECT DISTINCT
    M.MedicineName,
    (
        SELECT COUNT(*)
        FROM PRESCRIBEDMEDICINE PM
        JOIN ALLMEDICINEPRESCRIBERMEDICINERELATION AMR ON PM.PrescribedMedicineID = AMR.PrescribedMedicineID
        JOIN MEDICINES M2 ON AMR.MedicineID = M2.MedicineID
        JOIN PRESCRIPTION P ON PM.PrescriptionID = P.PrescriptionID
        WHERE M2.MedicineName = M.MedicineName
          AND P.PRESCRIPTIONDATE >= SYSDATE - 7
    ) AS UsageCount
FROM
    MEDICINES M
WHERE
   LOWER(M.MedicineName ) LIKE '%pa%'; 
	 
	 
	 --2
	 --prottek doctor ki ki poriman rogi dekche
	 SELECT
    D.FirstName || ' ' || D.LastName AS DoctorName,
    (
        SELECT COUNT(DISTINCT A.PatientID)
        FROM APPOINTMENT A
        WHERE A.DoctorID = D.DoctorID
    ) AS PatientsCount
FROM
    DOCTOR D;
		
		--ekta fixed time interval e 
		SELECT
    D.FirstName || ' ' || D.LastName AS DoctorName,
    (
        SELECT COUNT(DISTINCT A.PatientID)
        FROM APPOINTMENT A
        WHERE A.DoctorID = D.DoctorID
          AND A.AppointmentDate BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2024-12-31', 'YYYY-MM-DD')
    ) AS PatientsCount
FROM
    DOCTOR D;

		
		--3
		--ekta doctor kon rogi ke kotobar kore dekhche 
		
SELECT DISTINCT
    D.FirstName || ' ' || D.LastName AS DoctorName,
    P.FirstName || ' ' || P.LastName AS PatientName,
    (
        SELECT COUNT(*)
        FROM APPOINTMENT A
        WHERE A.DOCTORID = D.DoctorId AND A.PATIENTID = P.PATIENT_ID
    ) AS TotalAppointments
FROM DOCTOR D
JOIN APPOINTMENT A ON D.DoctorId = A.DOCTORID
JOIN PATIENT P ON A.PATIENTID = P.PATIENT_ID;


-- EKTA CERTAIN DOCTOR EKTA CERTAIN ROGI KOTO BAR DEKHCHE

SELECT DISTINCT
    D.FirstName || ' ' || D.LastName AS DoctorName,
    P.FirstName || ' ' || P.LastName AS PatientName,
    (
        SELECT COUNT(*)
        FROM APPOINTMENT A
        WHERE A.DOCTORID = D.DoctorId AND A.PATIENTID = P.PATIENT_ID
    ) AS TotalAppointments
FROM DOCTOR D
JOIN APPOINTMENT A ON D.DoctorId = A.DOCTORID
JOIN PATIENT P ON A.PATIENTID = P.PATIENT_ID
WHERE D.DOCTORID=7 AND P.PATIENT_ID=1 ;



--4
--doctor jokhon rogi dekhche tokhon oi roger previous history
SELECT
    A.AppointmentID,
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    A.AppointmentDate AS TODAYSAPPOINTMENTDATE,
    A.Notes,
    A.PATIENTDISEASE,
    (
        SELECT COUNT(*)
        FROM APPOINTMENT
        WHERE PATIENTID = A.PATIENTID
        AND APPOINTMENTDATE < A.APPOINTMENTDATE
        AND PATIENTDISEASE = A.PATIENTDISEASE
    ) AS PreviousAppointmentsCount
FROM APPOINTMENT A
JOIN PATIENT P ON A.PATIENTID = P.PATIENT_ID
JOIN DOCTOR D ON A.DOCTORID = D.DoctorId
WHERE A.APPOINTMENTID=181;


--5
-- DOCTOR PREVIOUSLY SAME DISEASE ER JONNO KI KI MEDICINES DICHE 
SELECT DISTINCT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
		A.PATIENTDISEASE,
    M2.MedicineName,
    M2.Dosages,
    M2.SideEffects,
		PM.HOWTOTAKE
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDMEDICINE PM ON PS.PrescriptionID = PM.PRESCRIPTIONID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN (
    SELECT
        M.MedicineName,
        M.Dosages,
        M.SideEffects,
				A2.PATIENTID,
        A2.PATIENTDISEASE
    FROM MEDICINES M
    JOIN ALLMEDICINEPRESCRIBERMEDICINERELATION AM ON M.MedicineID = AM.MedicineID
    JOIN PRESCRIBEDMEDICINE PM ON AM.PRESCRIBEDMEDICINEID = PM.PRESCRIBEDMEDICINEID
    JOIN PRESCRIPTION PS ON PM.PRESCRIPTIONID = PS.PRESCRIPTIONID
    JOIN APPOINTMENT A2 ON PS.AppointmentID = A2.AppointmentID
) M2 ON P.PATIENT_ID = M2.PATIENTID AND A.PATIENTDISEASE = M2.PATIENTDISEASE
WHERE A.PATIENTDISEASE='Sore Throat' AND A.PATIENTID=1 AND A.DOCTORID=7;
--DOCTOR CURRENT DISEASE ER JONNO KI KI LAB TEST DICHE

SELECT DISTINCT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
		L2.PATIENTDISEASE,
    L2.TestName
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDLABTEST PLT ON PS.PrescriptionID = PLT.PRESCRIPTIONID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN (
    SELECT
        LT.TestName,
				A2.PATIENTID,
        A2.PATIENTDISEASE
    FROM LABTESTS LT
    JOIN PRESCRIBEDLABTESTALLLABTESTRELATION PLTR ON LT.LABTESTID = PLTR.LABTESTID
    JOIN PRESCRIBEDLABTEST PLT2 ON PLTR.PRESCRIBEDLABTESTID = PLT2.PRESCRIBEDLABTESTID
    JOIN PRESCRIPTION PS2 ON PLT2.PRESCRIPTIONID = PS2.PRESCRIPTIONID
    JOIN APPOINTMENT A2 ON PS2.AppointmentID = A2.AppointmentID
) L2 ON P.PATIENT_ID = L2.PATIENTID AND A.PATIENTDISEASE = L2.PATIENTDISEASE;

--DOCTOR CURRENT DISEASE ER JONNO KI KI ADVICE DIYECHE 
SELECT DISTINCT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    AD2.PATIENTDISEASE,
    AD2.AdviceType,
    AD2.AdviceText
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDADVICE PAD ON PS.PrescriptionID = PAD.PrescriptionID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN (
    SELECT
        AD2.AdviceType,
        AD2.AdviceText,
        A2.PATIENTDISEASE,
				A2.PATIENTID
    FROM ADVICES AD2
    JOIN ADVICEPRESCRIBEDADVICERELATION ADPR2 ON AD2.AdviceID = ADPR2.AdviceID
    JOIN PRESCRIBEDADVICE PAD2 ON ADPR2.PrescribedAdviceID = PAD2.PrescribedAdviceID
    JOIN PRESCRIPTION PS2 ON PAD2.PrescriptionID = PS2.PrescriptionID
    JOIN APPOINTMENT A2 ON PS2.AppointmentID = A2.AppointmentID
) AD2 ON P.PATIENT_ID = AD2.PATIENTID AND A.PATIENTDISEASE = AD2.PATIENTDISEASE;
--onno jekono doctor take ei disease er jonno ki MEDICINES diyeche 
	SELECT DISTINCT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
		A.PATIENTDISEASE,
    M2.MedicineName,
    M2.Dosages,
    M2.SideEffects,
		PM.HOWTOTAKE
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDMEDICINE PM ON PS.PrescriptionID = PM.PRESCRIPTIONID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN (
    SELECT
        M.MedicineName,
        M.Dosages,
        M.SideEffects,
				A2.PATIENTID,
        A2.PATIENTDISEASE
    FROM MEDICINES M
    JOIN ALLMEDICINEPRESCRIBERMEDICINERELATION AM ON M.MedicineID = AM.MedicineID
    JOIN PRESCRIBEDMEDICINE PM ON AM.PRESCRIBEDMEDICINEID = PM.PRESCRIBEDMEDICINEID
    JOIN PRESCRIPTION PS ON PM.PRESCRIPTIONID = PS.PRESCRIPTIONID
    JOIN APPOINTMENT A2 ON PS.AppointmentID = A2.AppointmentID
) M2 ON P.PATIENT_ID = M2.PATIENTID AND A.PATIENTDISEASE = M2.PATIENTDISEASE
WHERE A.PATIENTDISEASE='Heart' AND A.PATIENTID=1;
--6

--SEE MEDICINES GIVEN  BY ME AND WHICH DISEASE IN THE LAST APPOINTMENT
SELECT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    A.PATIENTDISEASE,
    PM.HOWTOTAKE,
    M.MedicineName,
    M.Dosages,
    M.SideEffects,
		A.APPOINTMENTID,
		P.PATIENT_ID,
		PS.PRESCRIPTIONID
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDMEDICINE PM ON PS.PrescriptionID = PM.PRESCRIPTIONID
JOIN ALLMEDICINEPRESCRIBERMEDICINERELATION APR ON APR.PRESCRIBEDMEDICINEID=PM.PRESCRIBEDMEDICINEID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN MEDICINES M ON APR.MedicineID = M.MedicineID
WHERE PS.PRESCRIPTIONID =(
		SELECT MAX(PS1.PRESCRIPTIONID)
		FROM PATIENT P
		JOIN APPOINTMENT A2 ON P.PATIENT_ID = A2.PATIENTID
		JOIN PRESCRIPTION PS1 ON A2.AppointmentID = PS1.AppointmentID
		JOIN PRESCRIBEDMEDICINE PM ON PS1.PrescriptionID = PM.PRESCRIPTIONID
		WHERE A2.PATIENTID=A.PATIENTID AND A2.APPOINTMENTID <161
) AND D.DOCTORID=7 AND A.PATIENTID=1
ORDER BY PatientName, DoctorName, A.PATIENTDISEASE;

--SEE ADVICES LIKEWISE
SELECT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    A.PATIENTDISEASE,
    PA.AdviceType,
    PA.AdviceText,
		A.APPOINTMENTID,
		P.PATIENT_ID,
		PS.PRESCRIPTIONID
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN DOCTOR D ON D.DOCTORID=A.DOCTORID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDADVICE PAD ON PS.PrescriptionID = PAD.PRESCRIPTIONID
JOIN ADVICEPRESCRIBEDADVICERELATION APR ON PAD.PRESCRIBEDADVICEID=APR.PRESCRIBEDADVICEID
JOIN ADVICES PA ON PA.ADVICEID=APR.ADVICEID
WHERE PS.PRESCRIPTIONID = (
    SELECT MAX(PS2.PRESCRIPTIONID)
    FROM PATIENT P2
    JOIN APPOINTMENT A2 ON P2.PATIENT_ID = A2.PATIENTID
    JOIN PRESCRIPTION PS2 ON A2.AppointmentID = PS2.AppointmentID
    JOIN PRESCRIBEDADVICE PAD2 ON PS2.PrescriptionID = PAD2.PRESCRIPTIONID
    WHERE A2.PATIENTID = A.PATIENTID AND A2.APPOINTMENTID < 161
)AND D.DOCTORID=7 AND A.PATIENTID=1
ORDER BY PatientName, DoctorName, A.PATIENTDISEASE
;

--SEE LABTESTS LIKE WISE
SELECT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    A.PATIENTDISEASE,
    LT.TestName,
		A.APPOINTMENTID,
		P.PATIENT_ID,
		PS.PRESCRIPTIONID
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN DOCTOR D ON D.DOCTORID=A.DOCTORID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDLABTEST PLT ON PS.PrescriptionID = PLT.PRESCRIPTIONID
JOIN PRESCRIBEDLABTESTALLLABTESTRELATION PLTR ON PLT.PRESCRIBEDLABTESTID=PLTR.PRESCRIBEDLABTESTID
JOIN LABTESTS LT ON PLTR.LABTESTID = LT.LABTESTID
WHERE PS.PRESCRIPTIONID = (
    SELECT MAX(PS2.PRESCRIPTIONID)
    FROM PATIENT P2
    JOIN APPOINTMENT A2 ON P2.PATIENT_ID = A2.PATIENTID
    JOIN PRESCRIPTION PS2 ON A2.AppointmentID = PS2.AppointmentID
    JOIN PRESCRIBEDLABTEST PLT2 ON PS2.PrescriptionID = PLT2.PRESCRIPTIONID
    WHERE A2.PATIENTID = A.PATIENTID AND A2.APPOINTMENTID < 161
) AND A.PATIENTID=1
ORDER BY PatientName, DoctorName, A.PATIENTDISEASE;

--7
--EKTA START AND END DATE ER MODDHE PATIENT KI KI MEDICINE NICHE
SELECT
    P.FirstName || ' ' || P.LastName AS PatientName,
    M.MedicineName,
    PM.HOWTOTAKE,
    A.APPOINTMENTDATE,
		A.PATIENTDISEASE
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDMEDICINE PM ON PS.PrescriptionID = PM.PRESCRIPTIONID
JOIN ALLMEDICINEPRESCRIBERMEDICINERELATION APR ON APR.PRESCRIBEDMEDICINEID = PM.PRESCRIBEDMEDICINEID
JOIN MEDICINES M ON APR.MedicineID = M.MedicineID
WHERE EXISTS(
		SELECT PS1.PRESCRIPTIONDATE
		FROM PRESCRIPTION PS1  JOIN APPOINTMENT A2 ON A2.APPOINTMENTID=PS1.APPOINTMENTID
		WHERE A2.PATIENTID=A.PATIENTID AND PS1.PRESCRIPTIONDATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2024-12-31', 'YYYY-MM-DD')
		) AND P.PATIENT_ID=1;
--8
--SEE PENDING LAB TESTS ON A APPOINTMENT
JOIN PRESCRIBEDLABTEST PLT ON PS.PrescriptionID = PLT.PRESCRIPTIONID
JOIN PRESCRIBEDLABTESTALLLABTESTRELATION PRALL ON PRALL.PRESCRIBEDLABTESTID=PLT.PRESCRIBEDLABTESTID
JOIN LABTESTS LT ON PRALL.LABTESTID = LT.LABTESTID
SELECT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    A.PATIENTDISEASE,
    M.TESTNAME
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN (
    SELECT
        LT.TESTNAME,
        PR.PRESCRIPTIONID
    FROM PRESCRIBEDLABTEST PR 
    JOIN PRESCRIBEDLABTESTALLLABTESTRELATION PRALL ON PRALL.PRESCRIBEDLABTESTID = PR.PRESCRIBEDLABTESTID
    JOIN LABTESTS LT ON LT.LABTESTID = PRALL.LABTESTID 
    WHERE PR.STATUS = 'TEST PENDING'

) M ON M.PRESCRIPTIONID = PS.PRESCRIPTIONID
WHERE A.APPOINTMENTID=161;

--9
--SEE MY recent  PRECRIPTION FROM PATIENT
SELECT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    A.PATIENTDISEASE,
    PM.HOWTOTAKE,
    M.MedicineName,
    M.Dosages,
    M.SideEffects,
		A.APPOINTMENTID,
		P.PATIENT_ID,
		PS.PRESCRIPTIONID
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDMEDICINE PM ON PS.PrescriptionID = PM.PRESCRIPTIONID
JOIN ALLMEDICINEPRESCRIBERMEDICINERELATION APR ON APR.PRESCRIBEDMEDICINEID=PM.PRESCRIBEDMEDICINEID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN MEDICINES M ON APR.MedicineID = M.MedicineID
WHERE PS.PRESCRIPTIONID =(
		SELECT MAX(PS.PRESCRIPTIONID)
		FROM PATIENT P
		JOIN APPOINTMENT A2 ON P.PATIENT_ID = A2.PATIENTID
		JOIN PRESCRIPTION PS ON A2.AppointmentID = PS.AppointmentID
		JOIN PRESCRIBEDMEDICINE PM ON PS.PrescriptionID = PM.PRESCRIPTIONID
		WHERE A2.PATIENTID=2
)
ORDER BY PatientName, DoctorName, A.PATIENTDISEASE;
--LAB TEST AND ADVICE AND RESULT LIKE WISE 
SELECT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    A.PATIENTDISEASE,
		AD.ADVICETYPE,
		AD.ADVICETEXT,
		A.APPOINTMENTID,
		P.PATIENT_ID,
		PS.PRESCRIPTIONID
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDADVICE PA ON PS.PrescriptionID = PA.PRESCRIPTIONID
JOIN ADVICEPRESCRIBEDADVICERELATION APR ON APR.PRESCRIBEDADVICEID= PA.PRESCRIBEDADVICEID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN ADVICES AD ON AD.ADVICEID=APR.ADVICEID
WHERE PS.PRESCRIPTIONID =(
		SELECT MAX(PS.PRESCRIPTIONID)
		FROM PATIENT P
		JOIN APPOINTMENT A2 ON P.PATIENT_ID = A2.PATIENTID
		JOIN PRESCRIPTION PS ON A2.AppointmentID = PS.AppointmentID
		JOIN PRESCRIBEDMEDICINE PM ON PS.PrescriptionID = PM.PRESCRIPTIONID
		WHERE A2.PATIENTID=5 AND PS.PRESCRIPTION_STATUS='PAID'
)
ORDER BY PatientName, DoctorName, A.PATIENTDISEASE;

--LAB TEST 
SELECT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    A.PATIENTDISEASE,
		LT.TESTNAME,
		LT.DESCRIPTION,
		A.APPOINTMENTID,
		P.PATIENT_ID,
		PS.PRESCRIPTIONID
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDLABTEST PL  ON PS.PrescriptionID = PL.PRESCRIPTIONID
JOIN PRESCRIBEDLABTESTALLLABTESTRELATION  PLA ON PLA.PRESCRIBEDLABTESTID= PL.PRESCRIBEDLABTESTID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN LABTESTS LT ON LT.LABTESTID=PLA.LABTESTID
WHERE PS.PRESCRIPTIONID =(
		SELECT MAX(PS.PRESCRIPTIONID)
		FROM PATIENT P
		JOIN APPOINTMENT A2 ON P.PATIENT_ID = A2.PATIENTID
		JOIN PRESCRIPTION PS ON A2.AppointmentID = PS.AppointmentID
		JOIN PRESCRIBEDMEDICINE PM ON PS.PrescriptionID = PM.PRESCRIPTIONID
		WHERE A2.PATIENTID=2 AND PS.PRESCRIPTION_STATUS='PAID'
)
ORDER BY PatientName, DoctorName, A.PATIENTDISEASE;

--TEST RESULT 
SELECT
    P.FirstName || ' ' || P.LastName AS PatientName,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    A.PATIENTDISEASE,
		LT.TESTNAME,
		LT.DESCRIPTION,
		R.RESULTDETAILS,
		R.RESULTDATE,
		A.APPOINTMENTID,
		P.PATIENT_ID,
		PS.PRESCRIPTIONID
FROM PATIENT P
JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENTID
JOIN PRESCRIPTION PS ON A.AppointmentID = PS.AppointmentID
JOIN PRESCRIBEDLABTEST PL  ON PS.PrescriptionID = PL.PRESCRIPTIONID
JOIN RESULT R ON R.PRESCRIBEDLABTESTID=PL.PRESCRIBEDLABTESTID
JOIN DOCTOR D ON A.DOCTORID = D.DOCTORID
JOIN LABTESTS LT ON LT.LABTESTID=R.LABTESTID
WHERE PS.PRESCRIPTIONID =(
		SELECT MAX(PS.PRESCRIPTIONID)
		FROM PATIENT P
		JOIN APPOINTMENT A2 ON P.PATIENT_ID = A2.PATIENTID
		JOIN PRESCRIPTION PS ON A2.AppointmentID = PS.AppointmentID
		JOIN PRESCRIBEDMEDICINE PM ON PS.PrescriptionID = PM.PRESCRIPTIONID
		WHERE A2.PATIENTID=2 AND PS.PRESCRIPTION_STATUS='PAID'
)
ORDER BY PatientName, DoctorName, A.PATIENTDISEASE;



--FOR LAB TESTS 

--10
--SUB QUERIES RELATED TO BILLS 
--TO FIND TOTAL BILL 
SELECT NVL(SUM(COST),0) AS LABCOST,NVL(SUM(DOCTORCOST),0) AS DOCTORCOST ,NVL(SUM(COST),0)+NVL(SUM(DOCTORCOST),0) AS TOTALCOST 
 FROM APPOINTMENT A JOIN PRESCRIPTION P ON A.APPOINTMENTID = P.APPOINTMENTID 
	LEFT JOIN (
	SELECT PRESCRIPTIONID, SUM(COST) AS COST
	 FROM LABBILL GROUP BY PRESCRIPTIONID 
	 ) LB ON LB.PRESCRIPTIONID = P.PRESCRIPTIONID 
	 LEFT  JOIN ( 
	 SELECT PRESCRIPTIONID, SUM(DOCTORCOST) AS DOCTORCOST 
	 FROM DOCTORBILL GROUP BY PRESCRIPTIONID ) DB ON DB.PRESCRIPTIONID = P.PRESCRIPTIONID
	WHERE A.APPOINTMENTID =83 AND P.PRESCRIPTION_STATUS = 'UNPAID'

--11
--DOCTORS RANKING BASED ON KOTJON ROGI DEKHCHE
WITH T AS(
SELECT
    DoctorName,
    NumberOfPatients
FROM (
    SELECT
        D.FirstName || ' ' || D.LastName AS DoctorName,
        COUNT(A.PATIENTID) AS NumberOfPatients					
    FROM DOCTOR D
    JOIN APPOINTMENT A ON D.DOCTORID = A.DOCTORID
    GROUP BY D.DOCTORID, D.FirstName, D.LastName
)
)
 SELECT T1.NumberOfPatients AS NUMBEROFAPPOINTMENTS ,T1.DoctorName,COUNT(T2.DoctorName)+1 AS RANK
 FROM T T1 FULL JOIN T T2 ON T1.NumberOfPatients<T2.NumberOfPatients
 WHERE T1.DoctorName IS NOT NULL
 GROUP BY T1.NumberOfPatients,T1.DoctorName
 ORDER BY COUNT(T2.DoctorName)+1;


--12
--KON ROGI KOTO SPEND KORCHE LAB TEST E 
SELECT
    P.PATIENT_ID,
    P.FirstName || ' ' || P.LastName AS PatientName,
    (
        SELECT COALESCE(SUM(LB.Cost), 0)
        FROM APPOINTMENT A
        LEFT JOIN PRESCRIPTION PR ON A.AppointmentID = PR.AppointmentID
        LEFT JOIN LABBILL LB ON PR.PRESCRIPTIONID = LB.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID 
				HAVING COALESCE(SUM(LB.Cost), 0)>0
    ) AS TotalLabTestCost
FROM PATIENT P
WHERE(
        SELECT COALESCE(SUM(LB.Cost), 0)
        FROM APPOINTMENT A
        LEFT JOIN PRESCRIPTION PR ON A.AppointmentID = PR.AppointmentID
        LEFT JOIN LABBILL LB ON PR.PRESCRIPTIONID = LB.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID 
				HAVING COALESCE(SUM(LB.Cost), 0)>0
    ) IS NOT NULL;

--KON ROGI KOTO PAY KORCHE 
SELECT
    P.PATIENT_ID,
    P.FirstName || ' ' || P.LastName AS PatientName,
    (
        SELECT COALESCE(SUM(LB.Cost), 0)
        FROM APPOINTMENT A
        LEFT JOIN PRESCRIPTION PR ON A.AppointmentID = PR.AppointmentID
        LEFT JOIN LABBILL LB ON PR.PRESCRIPTIONID = LB.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID AND PR.PRESCRIPTION_STATUS='PAID' 
				HAVING COALESCE(SUM(LB.Cost), 0)>0
    ) AS TotalLabTestCost
FROM PATIENT P
WHERE (
        SELECT COALESCE(SUM(LB.Cost), 0)
        FROM APPOINTMENT A
        LEFT JOIN PRESCRIPTION PR ON A.AppointmentID = PR.AppointmentID
        LEFT JOIN LABBILL LB ON PR.PRESCRIPTIONID = LB.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID AND PR.PRESCRIPTION_STATUS='PAID' 
				HAVING COALESCE(SUM(LB.Cost), 0)>0
    ) IS NOT NULL;
--KON ROGIR KOTO BAKI ACHE LAB COST 
SELECT
    P.PATIENT_ID,
    P.FirstName || ' ' || P.LastName AS PatientName,
    (
        SELECT COALESCE(SUM(LB.Cost), 0)
        FROM APPOINTMENT A
        LEFT JOIN PRESCRIPTION PR ON A.AppointmentID = PR.AppointmentID
        LEFT JOIN LABBILL LB ON PR.PRESCRIPTIONID = LB.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID AND PR.PRESCRIPTION_STATUS='UNPAID' 
				HAVING COALESCE(SUM(LB.Cost), 0)>0
    ) AS TotalLabTestCost
FROM PATIENT P
WHERE (
        SELECT COALESCE(SUM(LB.Cost), 0)
        FROM APPOINTMENT A
        LEFT JOIN PRESCRIPTION PR ON A.AppointmentID = PR.AppointmentID
        LEFT JOIN LABBILL LB ON PR.PRESCRIPTIONID = LB.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID AND PR.PRESCRIPTION_STATUS='UNPAID' 
				HAVING COALESCE(SUM(LB.Cost), 0)>0
    ) IS NOT NULL;
--KON ROGI KOTO PAY KORCHE lab test e
SELECT
    P.PATIENT_ID,
    P.FirstName || ' ' || P.LastName AS PatientName,
    (
        SELECT COALESCE(SUM(LB.Cost), 0)
        FROM APPOINTMENT A
        LEFT JOIN PRESCRIPTION PR ON A.AppointmentID = PR.AppointmentID
        LEFT JOIN LABBILL LB ON PR.PRESCRIPTIONID = LB.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID AND PR.PRESCRIPTION_STATUS='PAID'
    ) AS TotalLabTestCost
FROM PATIENT P;

--13
--FROM DOCTORS SIDE ,KON KON PATIENT MORE THAN ONE APPOINTMENT NICHE WITH THEIR DISEASE
SELECT DISTINCT
    D.FirstName || ' ' || D.LastName AS DoctorName,
    P.FirstName || ' ' || P.LastName AS PatientName,
    A.PATIENTDISEASE,
    (
        SELECT COUNT(*)
        FROM APPOINTMENT A2
        WHERE A2.DOCTORID = D.DOCTORID
            AND A2.PATIENTID = A.PATIENTID
						AND A.PATIENTDISEASE=A2.PATIENTDISEASE
    ) AS AppointmentCount
FROM DOCTOR D
JOIN APPOINTMENT A ON D.DOCTORID = A.DOCTORID
JOIN PATIENT P ON A.PATIENTID = P.PATIENT_ID
WHERE (
    SELECT COUNT(*)
    FROM APPOINTMENT A3
    WHERE A3.DOCTORID = D.DOCTORID
        AND A3.PATIENTID = A.PATIENTID
				AND A.PATIENTDISEASE=A3.PATIENTDISEASE
) > 1 AND D.DOCTORID=7;
--14
--LAST  7 DAYS APPOINTMENT
SELECT
    D.FirstName || ' ' || D.LastName AS DoctorName,
    P.FirstName || ' ' || P.LastName AS PatientName,
    A.PATIENTDISEASE,
    (
        SELECT COUNT(*)
        FROM APPOINTMENT A2
        WHERE A2.DOCTORID = D.DOCTORID
            AND A2.PATIENTID = A.PATIENTID
            AND A2.PATIENTDISEASE = A.PATIENTDISEASE
            AND A2.AppointmentDate >= SYSDATE - 7
    ) AS AppointmentCount
FROM DOCTOR D
JOIN APPOINTMENT A ON D.DOCTORID = A.DOCTORID
JOIN PATIENT P ON A.PATIENTID = P.PATIENT_ID
WHERE A.AppointmentDate >= SYSDATE - 7  AND D.DOCTORID=7;

--15
--PATIENT WITH MULTIPLE UNPAID BILLS
SELECT
    P.PATIENT_ID,
    P.FirstName || ' ' || P.LastName AS PatientName,
    (
        SELECT COUNT(*)
        FROM APPOINTMENT A
        JOIN PRESCRIPTION PRS ON A.AppointmentID = PRS.AppointmentID
        JOIN BILL B ON PRS.PrescriptionID = B.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID
        AND PRS.PRESCRIPTION_STATUS = 'UNPAID'
    ) AS NumberOfPrescriptions,
    (
        SELECT SUM(B.TOTAL_COST)
        FROM APPOINTMENT A
        JOIN PRESCRIPTION PRS ON A.AppointmentID = PRS.AppointmentID
        JOIN BILL B ON PRS.PrescriptionID = B.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID
        AND PRS.PRESCRIPTION_STATUS = 'UNPAID'
    ) AS TotalBillAmount
FROM PATIENT P
WHERE (SELECT COUNT(*)
        FROM APPOINTMENT A
        JOIN PRESCRIPTION PRS ON A.AppointmentID = PRS.AppointmentID
        JOIN BILL B ON PRS.PrescriptionID = B.PRESCRIPTIONID
        WHERE A.PATIENTID = P.PATIENT_ID
        AND PRS.PRESCRIPTION_STATUS = 'UNPAID') > 1;

--daywise PRESCRIPTION and appointment count 
SELECT
    TO_CHAR(A.AppointmentDate, 'YYYY-MM-DD') AS AppointmentDay,
    D.FirstName || ' ' || D.LastName AS DoctorName,
    COUNT(DISTINCT P.PrescriptionID) AS PrescriptionCount,
    COUNT(A.AppointmentID) AS AppointmentCount
FROM
    APPOINTMENT A
JOIN
    DOCTOR D ON A.DoctorId = D.DoctorId
LEFT JOIN
    PRESCRIPTION P ON A.AppointmentID = P.AppointmentID
GROUP BY
    TO_CHAR(A.AppointmentDate, 'YYYY-MM-DD'),
    D.FirstName || ' ' || D.LastName
ORDER BY
    AppointmentDay,
    DoctorName;
--17
--see disease and number of patient suffered with it 
SELECT
    DISTINCT PATIENTDISEASE AS DiseaseName,
    (
        SELECT COUNT(DISTINCT PatientID)
        FROM APPOINTMENT A2
        WHERE A2.PATIENTDISEASE = A.PATIENTDISEASE
    ) AS NumberOfPatients
FROM APPOINTMENT A;

--18
--doctors who havenot prescribed any patients


 
SELECT
    D.FirstName || ' ' || D.LastName AS DoctorName
FROM
    DOCTOR D
WHERE
    NOT EXISTS (
        SELECT 1
        FROM
            APPOINTMENT A
        WHERE
            A.DOCTORID = D.DOCTORID
            AND A.APPOINTMENTID IN (
                SELECT
                    PS.APPOINTMENTID
                FROM
                    PRESCRIPTION PS
            )
    );


SELECT * FROM MONEYS WHERE ROWNUM=1;
